name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/oracle_key
          chmod 600 ~/.ssh/oracle_key

          ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy na Oracle
        run: |
          ssh \
            -i ~/.ssh/oracle_key \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            "/home/ubuntu/deploy-portfolio.sh"
